/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hr/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/absence-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAbsenceTypes"];
        put?: never;
        post: operations["createAbsenceType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/absence-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAbsenceType"];
        put: operations["updateAbsenceType"];
        post?: never;
        delete: operations["deleteAbsenceType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/absence-types/{id}/signing-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["checkAbsenceTypeSigning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/signing/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSigningTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPools"];
        put?: never;
        post: operations["createPool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPool"];
        put: operations["updatePool"];
        post?: never;
        delete: operations["deletePool"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/allowances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description hr:read lists everyone; managers their departments; others (hr:request) their own. */
        get: operations["listAllowances"];
        put?: never;
        post: operations["createAllowance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/allowances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllowance"];
        put: operations["updateAllowance"];
        post?: never;
        delete: operations["deleteAllowance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/balance/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/carry-over/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewCarryOver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/carry-over": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runCarryOver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRequests"];
        put?: never;
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRequest"];
        put: operations["updateRequest"];
        post?: never;
        delete: operations["deleteRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description routed approvers (department managers) or hr:manage; never the owner. */
        post: operations["approveRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/requests/{id}/signed-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadSignedDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDepartments"];
        put?: never;
        post: operations["createDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateDepartment"];
        post?: never;
        delete: operations["deleteDepartment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/departments/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setDepartmentMembers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHolidays"];
        put?: never;
        post: operations["createHoliday"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/holidays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateHoliday"];
        post?: never;
        delete: operations["deleteHoliday"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/holidays/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description text/csv or text/plain: YYYY-MM-DD,name[,yearly] per line. */
        post: operations["importHolidays"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Long-lived SSE stream of the caller's hr events (request and review changes addressed to them; calendar changes of the tenant; ids and status only). The module closes it at 290 s and the client resumes with last_id. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exportBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hr/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description unauthenticated | forbidden | not_found | malformed_body | body_too_large | validation | overlap | insufficient_allowance | no_allowance | zero_days | invalid_transition | self_review | not_routed | in_use | duplicate | not_empty | cycle | signing_unavailable | signing_template_invalid | signer_inactive | not_signed | conflict | payload_too_large | invalid_backup | temporarily_unavailable */
            reason: string;
            field?: string;
            detail?: Record<string, never>;
        };
        /** Format: uuid */
        Uuid: string;
        /** Format: date */
        Date: string;
        Days: number;
        Color: string;
        Me: {
            user_id: string;
            permissions: string[];
            /** @description department ids the caller manages (with descendants) */
            manages: string[];
            department_id?: string;
        };
        Person: {
            user_id: string;
            name: string;
            department_id?: string;
        };
        PersonList: {
            items: components["schemas"]["Person"][];
        };
        SigningSettings: {
            template_id: string;
            template_name?: string;
            employee_party: string;
            approver_party: string;
            fields: {
                [key: string]: "employee_name" | "department" | "absence_type" | "start_date" | "end_date" | "days" | "reason" | "approver_name" | "today";
            };
        };
        AbsenceType: {
            id: components["schemas"]["Uuid"];
            name: string;
            description?: string;
            color?: string;
            icon?: string;
            sort_order?: number;
            active: boolean;
            metadata?: Record<string, never>;
            deducts: boolean;
            requires_approval: boolean;
            pool_id?: string;
            carry_over_cap?: number | null;
            requires_signing: boolean;
            signing?: components["schemas"]["SigningSettings"] | null;
        };
        AbsenceTypeWrite: {
            name: string;
            description?: string;
            color?: components["schemas"]["Color"];
            icon?: string;
            sort_order?: number;
            active?: boolean;
            metadata?: Record<string, never>;
            deducts?: boolean;
            requires_approval?: boolean;
            pool_id?: string;
            carry_over_cap?: number | null;
            requires_signing?: boolean;
            signing?: components["schemas"]["SigningSettings"] | null;
        };
        AbsenceTypeList: {
            items: components["schemas"]["AbsenceType"][];
        };
        SigningCheck: {
            ok: boolean;
            reason?: string;
        };
        SigningTemplate: {
            id: string;
            name: string;
            parties: {
                id: string;
                name: string;
            }[];
            fields: {
                id: string;
                name: string;
                type: string;
                party: string;
                text_valued: boolean;
            }[];
        };
        SigningTemplateList: {
            items: components["schemas"]["SigningTemplate"][];
        };
        Pool: {
            id: components["schemas"]["Uuid"];
            name: string;
            description?: string;
            color?: string;
            icon?: string;
            carry_over_cap?: number | null;
        };
        PoolWrite: {
            name: string;
            description?: string;
            color?: components["schemas"]["Color"];
            icon?: string;
            carry_over_cap?: number | null;
        };
        PoolList: {
            items: components["schemas"]["Pool"][];
        };
        Allowance: {
            id: components["schemas"]["Uuid"];
            user_id: string;
            year: number;
            absence_type_id?: string;
            pool_id?: string;
            total_days: components["schemas"]["Days"];
            carried_over: components["schemas"]["Days"];
            used_days: components["schemas"]["Days"];
            remaining: components["schemas"]["Days"];
            notes?: string;
        };
        AllowanceWrite: {
            user_id: string;
            year: number;
            absence_type_id?: string;
            pool_id?: string;
            total_days: number;
            carried_over?: number;
            notes?: string;
        };
        AllowancePage: {
            items: components["schemas"]["Allowance"][];
            total: number;
        };
        BalanceLine: {
            /** @enum {string} */
            kind: "pool" | "type";
            id: string;
            name: string;
            color?: string;
            allowance_id?: string;
            total: components["schemas"]["Days"];
            carried: components["schemas"]["Days"];
            used: components["schemas"]["Days"];
            pending: components["schemas"]["Days"];
            remaining: components["schemas"]["Days"];
            member_type_ids: string[];
        };
        Balance: {
            user_id: string;
            year: number;
            lines: components["schemas"]["BalanceLine"][];
        };
        Request: {
            id: components["schemas"]["Uuid"];
            user_id: string;
            user_name?: string;
            absence_type_id: string;
            start_date: components["schemas"]["Date"];
            end_date: components["schemas"]["Date"];
            half_start: boolean;
            half_end: boolean;
            days: components["schemas"]["Days"];
            /** @enum {string} */
            status: "pending" | "awaiting_signing" | "approved" | "rejected" | "cancelled" | "revoked";
            reason?: string;
            notes?: string;
            approver_ids: string[];
            approver_names?: string[];
            reviewed_by?: string;
            reviewer_name?: string;
            /** Format: date-time */
            reviewed_at?: string | null;
            review_notes?: string;
            /** @description a signed leave document exists or is being signed */
            signing?: boolean;
            /** @enum {string} */
            signing_note?: "" | "declined" | "expired" | "cancelled";
            /** Format: date-time */
            created_at?: string;
            can_review?: boolean;
            can_edit?: boolean;
            can_cancel?: boolean;
        };
        RequestWrite: {
            user_id?: string;
            absence_type_id: string;
            start_date: components["schemas"]["Date"];
            end_date: components["schemas"]["Date"];
            half_start?: boolean;
            half_end?: boolean;
            reason?: string;
            notes?: string;
        };
        RequestEdit: {
            reason?: string;
            notes?: string;
        };
        Decision: {
            notes?: string;
        };
        Preview: {
            days: components["schemas"]["Days"];
            per_year: {
                [key: string]: number;
            };
            approvers: string[];
            approver_names?: string[];
            overlaps: boolean;
            remaining: {
                [key: string]: number;
            };
            status: string;
        };
        RequestPage: {
            items: components["schemas"]["Request"][];
            total: number;
        };
        Calendar: {
            people: components["schemas"]["Person"][];
            events: {
                id: string;
                user_id: string;
                absence_type_id: string;
                start_date: components["schemas"]["Date"];
                end_date: components["schemas"]["Date"];
                half_start: boolean;
                half_end: boolean;
                days: components["schemas"]["Days"];
                status: string;
            }[];
            holidays: {
                date: components["schemas"]["Date"];
                name: string;
            }[];
        };
        Department: {
            id: components["schemas"]["Uuid"];
            name: string;
            parent_id: string;
            manager_id: string;
            manager_name?: string;
            member_ids?: string[];
        };
        DepartmentWrite: {
            name: string;
            parent_id?: string;
            manager_id?: string;
        };
        DepartmentList: {
            items: components["schemas"]["Department"][];
        };
        MembersWrite: {
            add?: string[];
            remove?: string[];
        };
        Holiday: {
            id: components["schemas"]["Uuid"];
            date: components["schemas"]["Date"];
            name: string;
            recurring: boolean;
        };
        HolidayWrite: {
            date: components["schemas"]["Date"];
            name: string;
            recurring?: boolean;
        };
        HolidayList: {
            items: components["schemas"]["Holiday"][];
        };
        ImportResult: {
            created: number;
            skipped: number;
            dry_run: boolean;
            errors: {
                line?: number;
                reason?: string;
            }[];
        };
        CarryOverRequest: {
            source_year: number;
        };
        CarryOverPlan: {
            source_year: number;
            run_id?: string;
            created: number;
            updated: number;
            items: {
                user_id?: string;
                kind?: string;
                id?: string;
                unused?: number;
                cap?: number | null;
                carried?: number;
                /** @enum {string} */
                action?: "create" | "update" | "none";
            }[];
        };
        Stats: {
            absence_types: number;
            pending: number;
            awaiting_signing: number;
            approved: number;
            rejected: number;
            absent_today: components["schemas"]["Person"][];
        };
    };
    responses: {
        /** @description refusal */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        csrf: string;
        id: string;
        userId: string;
        page: number;
        pageSize: number;
        year: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description component status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPeople: {
        parameters: {
            query?: {
                department?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description active members (names only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    calendar: {
        parameters: {
            query: {
                from: components["schemas"]["Date"];
                to: components["schemas"]["Date"];
                department?: string;
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description team calendar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calendar"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAbsenceTypes: {
        parameters: {
            query?: {
                /** @description include inactive types (hr:read) */
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description absence types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceTypeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAbsenceType: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsenceTypeWrite"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceType"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAbsenceType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description absence type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceType"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateAbsenceType: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsenceTypeWrite"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceType"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteAbsenceType: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    checkAbsenceTypeSigning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description signing settings still valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningCheck"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSigningTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description active signing templates of the tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningTemplateList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolWrite"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pool */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updatePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolWrite"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pool"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deletePool: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAllowances: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                year?: components["parameters"]["year"];
                user?: string;
                type?: string;
                pool?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of allowances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowancePage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAllowance: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllowanceWrite"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allowance"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAllowance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description allowance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allowance"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateAllowance: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllowanceWrite"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allowance"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteAllowance: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getBalance: {
        parameters: {
            query?: {
                year?: components["parameters"]["year"];
            };
            header?: never;
            path: {
                user_id: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewCarryOver: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarryOverRequest"];
            };
        };
        responses: {
            /** @description plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarryOverPlan"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    runCarryOver: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarryOverRequest"];
            };
        };
        responses: {
            /** @description applied plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarryOverPlan"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRequests: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                view?: "mine" | "review" | "all";
                user?: string;
                department?: string;
                type?: string;
                status?: "pending" | "awaiting_signing" | "approved" | "rejected" | "cancelled" | "revoked";
                from?: components["schemas"]["Date"];
                to?: components["schemas"]["Date"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestWrite"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestWrite"];
            };
        };
        responses: {
            /** @description preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestEdit"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    approveRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description approved or awaiting signing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rejectRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelRequest: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Request"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    downloadSignedDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description signed PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description department tree (flat) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createDepartment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentWrite"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateDepartment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentWrite"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteDepartment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    setDepartmentMembers: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembersWrite"];
            };
        };
        responses: {
            /** @description updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listHolidays: {
        parameters: {
            query?: {
                year?: components["parameters"]["year"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description holidays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HolidayList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createHoliday: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HolidayWrite"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateHoliday: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HolidayWrite"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteHoliday: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    importHolidays: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                last_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description gzip archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importBackup: {
        parameters: {
            query?: {
                mode?: "skip" | "overwrite";
            };
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description import summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
