import type { components } from './schema.d'

type S = components['schemas']
export type Me = S['Me']
export type Person = S['Person']
export type AbsenceType = S['AbsenceType']
export type AbsenceTypeWrite = S['AbsenceTypeWrite']
export type SigningSettings = S['SigningSettings']
export type SigningTemplate = S['SigningTemplate']
export type Pool = S['Pool']
export type PoolWrite = S['PoolWrite']
export type Allowance = S['Allowance']
export type AllowanceWrite = S['AllowanceWrite']
export type AllowancePage = S['AllowancePage']
export type Balance = S['Balance']
export type BalanceLine = S['BalanceLine']
export type LeaveRequest = S['Request']
export type RequestWrite = S['RequestWrite']
export type RequestPage = S['RequestPage']
export type Preview = S['Preview']
export type Calendar = S['Calendar']
export type CalendarEvent = Calendar['events'][number]
export type Department = S['Department']
export type DepartmentWrite = S['DepartmentWrite']
export type Holiday = S['Holiday']
export type HolidayWrite = S['HolidayWrite']
export type ImportResult = S['ImportResult']
export type CarryOverPlan = S['CarryOverPlan']
export type Stats = S['Stats']
export type RequestStatus = LeaveRequest['status']

export const REQUEST_STATUSES: readonly RequestStatus[] = ['pending', 'awaiting_signing', 'approved', 'rejected', 'cancelled', 'revoked']

export const VALUE_KEYS = ['employee_name', 'department', 'absence_type', 'start_date', 'end_date', 'days', 'reason', 'approver_name', 'today'] as const
export type ValueKey = (typeof VALUE_KEYS)[number]
